# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Jad Joubran
tagline:          'Sharing my passion for code'
description:      'Sharing my passion for code'
url:              http://blog.jadjoubran.io
baseurl:          /

author:
  name:           'Jad Joubran'
  url:            https://github.com/jadjoubran

paginate:         5

# Custom vars

github:
  repo:           https://github.com/poole/hyde

gems:             [jekyll-paginate, jekyll-gist, jemoji] 